let Areas = [
{cod_area: "20000",
des_Cod_area: "Gerencia",	
},
{Cod_area: "25000",
des_Cod_area: "Mercadeo-Ventas",	
},
{Cod_area: "30000",
des_Cod_area: "Tecnología-Sistemas",	
},
{Cod_area: "35000",
des_Cod_area: "Producción",	
},
{Cod_area: "40000",
des_Cod_area: "Contabilidad",	
},
{Cod_area: "45000",
des_Cod_area: "Recursos Humanos",	
},
]
